# Generated by Django 5.0.1 on 2024-05-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
